
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./packages/frontend
      target: development
    command: npm run dev
    volumes:
      - ./packages/frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - backend
  backend:
    build:
        dockerfile: Dockerfile
        context: ./packages/backendExpress
        target: development
#    command: npm run start:inspect
    command: npm run dev
    env_file:
      - ./packages/backendExpress/.env
    environment:
      POSTGRES_HOST: db
    volumes:
      - ./packages/backendExpress:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - packages/backendExpress/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/pgData:/var/lib/postgresql/data