import './globals.css'
import Link from "next/link";
import Image from "next/image";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        <div className="navbar bg-base-100">
            <div className="flex-1">
                <Link href="/" className="btn btn-ghost normal-case text-xl">
                    Home
                </Link>
            </div>
        </div>

        {children}
        </body>
        </html>
    )
}
